import { FormEvent, useEffect, useState } from "react";
import {
  ApiError,
  Category,
  createTicket,
  CreateTicketInput,
  DevelopmentRequester,
  getCategories,
  getRelatedSystems,
  RelatedSystem,
} from "./api.js";

const emptyTicket: CreateTicketInput = {
  categoryId: 0,
  relatedSystemId: 0,
  summary: "",
  requestedPriority: "MEDIUM",
  description: "",
};

function validate(input: CreateTicketInput): Record<string, string> {
  const fields: Record<string, string> = {};
  if (!input.categoryId) fields.categoryId = "Choose an active category.";
  if (!input.relatedSystemId) fields.relatedSystemId = "Choose an active related system.";
  if (input.summary.trim().length < 5 || input.summary.trim().length > 120) fields.summary = "Summary must be 5 to 120 characters.";
  if (input.description.trim().length < 10 || input.description.trim().length > 2000) fields.description = "Description must be 10 to 2,000 characters.";
  return fields;
}

export function CreateTicketForm({ requester }: { requester: DevelopmentRequester }) {
  const [loadState, setLoadState] = useState<"loading" | "ready" | "error">("loading");
  const [categories, setCategories] = useState<Category[]>([]);
  const [relatedSystems, setRelatedSystems] = useState<RelatedSystem[]>([]);
  const [input, setInput] = useState<CreateTicketInput>(emptyTicket);
  const [fields, setFields] = useState<Record<string, string>>({});
  const [submitState, setSubmitState] = useState<"idle" | "submitting" | "error" | "success">("idle");
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    void Promise.all([getCategories(), getRelatedSystems()])
      .then(([loadedCategories, loadedSystems]) => {
        if (!active) return;
        setCategories(loadedCategories);
        setRelatedSystems(loadedSystems);
        setLoadState("ready");
      })
      .catch(() => { if (active) setLoadState("error"); });
    return () => { active = false; };
  }, []);

  function update<K extends keyof CreateTicketInput>(key: K, value: CreateTicketInput[K]) {
    setInput((current) => ({ ...current, [key]: value }));
    setFields((current) => ({ ...current, [key]: "" }));
    setMessage(null);
    setSubmitState("idle");
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const trimmed = { ...input, summary: input.summary.trim(), description: input.description.trim() };
    const clientErrors = validate(trimmed);
    if (Object.keys(clientErrors).length) {
      setFields(clientErrors);
      setSubmitState("error");
      return;
    }

    setSubmitState("submitting");
    setFields({});
    setMessage(null);
    try {
      const created = await createTicket(requester.id, trimmed);
      setInput(emptyTicket);
      setSubmitState("success");
      setMessage(`Ticket created: ${created.ticketNumber}. The official number was generated by the backend.`);
    } catch (error) {
      const apiError = error instanceof ApiError ? error : null;
      setFields(apiError?.fields ?? {});
      setSubmitState("error");
      setMessage(apiError?.message ?? "Unable to create the Ticket. Your entered values are still available.");
    }
  }

  if (loadState === "loading") return <p className="text-secondary" role="status">Loading categories and related systems...</p>;
  if (loadState === "error") return <div className="alert alert-danger" role="alert">Unable to load the Ticket reference data. Please try again after the API is available.</div>;

  return <section aria-labelledby="create-ticket-heading">
    <h1 className="h3" id="create-ticket-heading">Create Ticket</h1>
    <p className="text-secondary">Describe the IT support request. Fields marked with * are required.</p>
    {message && <div className={`alert ${submitState === "success" ? "alert-success" : "alert-danger"}`} role={submitState === "success" ? "status" : "alert"}>{message}</div>}
    <form noValidate onSubmit={submit} className="card shadow-sm"><div className="card-body p-4">
      <div className="mb-3"><label className="form-label fw-semibold" htmlFor="requester">Requester</label><input id="requester" className="form-control bg-light" value={requester.displayName} readOnly /></div>
      <div className="row g-3">
        <FieldSelect id="category" label="Category *" value={input.categoryId} items={categories} error={fields.categoryId} placeholder="Choose a category..." onChange={(value) => update("categoryId", value)} />
        <FieldSelect id="related-system" label="Related System *" value={input.relatedSystemId} items={relatedSystems} error={fields.relatedSystemId} placeholder="Choose a related system..." onChange={(value) => update("relatedSystemId", value)} />
      </div>
      <div className="mt-3"><label className="form-label fw-semibold" htmlFor="summary">Ticket Summary *</label><input id="summary" className={`form-control ${fields.summary ? "is-invalid" : ""}`} value={input.summary} maxLength={120} onChange={(event) => update("summary", event.target.value)} />{fields.summary && <div className="invalid-feedback">{fields.summary}</div>}</div>
      <div className="mt-3"><label className="form-label fw-semibold" htmlFor="requested-priority">Requested Priority *</label><select id="requested-priority" className="form-select" value={input.requestedPriority} onChange={(event) => update("requestedPriority", event.target.value as CreateTicketInput["requestedPriority"])}><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option></select></div>
      <div className="mt-3"><label className="form-label fw-semibold" htmlFor="description">Description *</label><textarea id="description" className={`form-control ${fields.description ? "is-invalid" : ""}`} value={input.description} rows={5} maxLength={2000} onChange={(event) => update("description", event.target.value)} />{fields.description && <div className="invalid-feedback">{fields.description}</div>}</div>
      <button className="btn btn-success mt-4" disabled={submitState === "submitting"} type="submit">{submitState === "submitting" ? "Creating Ticket..." : "Create Ticket"}</button>
    </div></form>
  </section>;
}

function FieldSelect({ id, label, value, items, error, placeholder, onChange }: { id: string; label: string; value: number; items: { id: number; name: string }[]; error?: string; placeholder: string; onChange: (value: number) => void }) {
  return <div className="col-md-6"><label className="form-label fw-semibold" htmlFor={id}>{label}</label><select id={id} className={`form-select ${error ? "is-invalid" : ""}`} value={value || ""} onChange={(event) => onChange(Number(event.target.value))}><option value="">{placeholder}</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{error && <div className="invalid-feedback">{error}</div>}</div>;
}
