import { FormEvent, useEffect, useState } from "react";
import { addStaffInternalNote, addStaffPublicComment, ApiError, assignStaffTicket, AuthUser, claimStaffTicket, getStaffTicketDetail, getStaffTicketOwners, ITPriority, setStaffTicketPriority, setStaffTicketStatus, StaffTicketDetail as StaffTicketDetailData, TicketOwner, TicketStatus } from "./api.js";

const priorities: ITPriority[] = ["NOT_SET", "LOW", "MEDIUM", "HIGH", "URGENT"];
const statuses: TicketStatus[] = ["NEW", "OPEN", "IN_PROGRESS", "WAITING_FOR_REQUESTER", "RESOLVED", "CLOSED", "REOPENED", "CANCELLED"];
const label = (value: string) => value.toLowerCase().split("_").map((word) => word[0].toUpperCase() + word.slice(1)).join(" ");

export function StaffTicketDetail({ ticketId, user, onBack }: { ticketId: number; user: AuthUser; onBack: () => void }) {
  const [ticket, setTicket] = useState<StaffTicketDetailData | null>(null); const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [owners, setOwners] = useState<TicketOwner[]>([]);
  const [message, setMessage] = useState(""); const [publicComment, setPublicComment] = useState(""); const [internalNote, setInternalNote] = useState("");
  const refresh = () => { setState("loading"); void getStaffTicketDetail(ticketId).then((detail) => { setTicket(detail); setState("ready"); }).catch((error: unknown) => { setMessage(error instanceof Error ? error.message : "Unable to retrieve the Ticket."); setState("error"); }); };
  useEffect(() => { refresh(); void getStaffTicketOwners().then(setOwners).catch(() => setOwners([])); }, [ticketId]);
  const act = async (work: () => Promise<StaffTicketDetailData | unknown>, success: string) => { setMessage(""); try { const result = await work(); if (result && typeof result === "object" && "ticketNumber" in result) setTicket(result as StaffTicketDetailData); else refresh(); setMessage(success); } catch (error) { setMessage(error instanceof ApiError ? error.message : "Unable to save the Ticket update."); } };
  const submitEntry = (event: FormEvent, kind: "public" | "internal") => { event.preventDefault(); const content = kind === "public" ? publicComment : internalNote; void act(() => kind === "public" ? addStaffPublicComment(ticketId, content) : addStaffInternalNote(ticketId, content), kind === "public" ? "Public Comment added." : "Internal Note added."); if (kind === "public") setPublicComment(""); else setInternalNote(""); };
  if (state === "loading") return <p role="status">Loading Ticket details...</p>;
  if (state === "error" || !ticket) return <><div className="alert alert-danger" role="alert">{message || "Unable to retrieve the Ticket."}</div><button className="btn btn-outline-success" onClick={onBack}>Back to queue</button></>;
  const canEdit = user.role === "IT_STAFF";
  return <section aria-label="IT Staff Ticket Detail"><button className="btn btn-link px-0 mb-3" onClick={onBack}>← Back to Ticket Queue</button><div className="d-flex justify-content-between align-items-start gap-3 mb-3"><div><h1 className="h3 mb-1">{ticket.ticketNumber}</h1><p className="mb-0 text-secondary">{ticket.summary}</p></div><span className="badge text-bg-success">{label(ticket.currentStatus)}</span></div>{message && <div className={`alert ${message.includes("added") || message.includes("saved") ? "alert-success" : "alert-danger"}`} role="status">{message}</div>}
    <section className="card mb-3"><div className="card-body"><h2 className="h5">Ticket information</h2><dl className="row mb-0"><dt className="col-sm-3">Requester</dt><dd className="col-sm-9">{ticket.requesterUser?.name ?? "Unavailable"}</dd><dt className="col-sm-3">Category</dt><dd className="col-sm-9">{ticket.category.name}</dd><dt className="col-sm-3">Requested Priority</dt><dd className="col-sm-9"><span className="badge text-bg-secondary">{label(ticket.requestedPriority)}</span></dd><dt className="col-sm-3">Description</dt><dd className="col-sm-9" style={{ whiteSpace: "pre-wrap" }}>{ticket.description}</dd></dl></div></section>
    <section className="card mb-3"><div className="card-body"><h2 className="h5">IT Staff controls</h2><p>Owner: <strong>{ticket.owner?.name ?? "Unassigned"}</strong></p>{canEdit && <><button className="btn btn-outline-success me-3" onClick={() => void act(() => claimStaffTicket(ticketId), "Ticket ownership saved.")}>Claim Ticket</button><label className="form-label d-block mt-3" htmlFor="ticket-owner">Assign or reassign owner</label><select id="ticket-owner" className="form-select" value={ticket.owner?.id ?? ""} onChange={(event) => event.target.value && void act(() => assignStaffTicket(ticketId, Number(event.target.value)), "Ticket ownership saved.")}><option value="">Choose an active owner</option>{owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.name} · {label(owner.role)}</option>)}</select></>}<label className="form-label d-block mt-3" htmlFor="it-priority">IT Priority</label><select id="it-priority" className="form-select" value={ticket.itPriority} disabled={!canEdit} onChange={(event) => void act(() => setStaffTicketPriority(ticketId, event.target.value as ITPriority), "IT Priority saved.")}>{priorities.map((priority) => <option key={priority} value={priority}>{label(priority)}</option>)}</select><label className="form-label d-block mt-3" htmlFor="ticket-status">Current Status</label><select id="ticket-status" className="form-select" value={ticket.currentStatus} disabled={!canEdit} onChange={(event) => void act(() => setStaffTicketStatus(ticketId, event.target.value as TicketStatus), "Ticket status saved.")}>{statuses.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select></div></section>
    <section className="card mb-3"><div className="card-body"><h2 className="h5">Attachments</h2>{ticket.attachments.length === 0 ? <p className="text-secondary mb-0">No attachments were added to this Ticket.</p> : <ul className="mb-0">{ticket.attachments.map((attachment) => <li key={attachment.id}>{attachment.originalFilename} <span className="text-secondary">({attachment.mimeType}, {attachment.byteSize} bytes)</span></li>)}</ul>}</div></section>
    <section className="card mb-3"><div className="card-body"><h2 className="h5">Public Comments</h2>{ticket.publicComments.map((entry) => <article className="border-bottom py-2" key={entry.id}><strong>{entry.author.name}</strong><small className="text-secondary ms-2">{new Date(entry.createdAt).toLocaleString()}</small><p className="mb-0" style={{ whiteSpace: "pre-wrap" }}>{entry.content}</p></article>)}{canEdit && <form className="mt-3" onSubmit={(event) => submitEntry(event, "public")}><label className="form-label" htmlFor="public-comment">Add Public Comment</label><textarea id="public-comment" className="form-control" value={publicComment} maxLength={2000} onChange={(event) => setPublicComment(event.target.value)} /><button className="btn btn-success mt-2">Post Public Comment</button></form>}</div></section>
    <section className="card border-warning"><div className="card-body"><h2 className="h5">Internal Notes <span className="badge text-bg-warning">IT Staff and Administrator only</span></h2>{ticket.internalNotes.map((entry) => <article className="border-bottom py-2" key={entry.id}><strong>{entry.author.name}</strong><small className="text-secondary ms-2">{new Date(entry.createdAt).toLocaleString()}</small><p className="mb-0" style={{ whiteSpace: "pre-wrap" }}>{entry.content}</p></article>)}{canEdit && <form className="mt-3" onSubmit={(event) => submitEntry(event, "internal")}><label className="form-label" htmlFor="internal-note">Add Internal Note</label><textarea id="internal-note" className="form-control" value={internalNote} maxLength={2000} onChange={(event) => setInternalNote(event.target.value)} /><div className="form-text">This note is private and will not be shown to the Requester.</div><button className="btn btn-warning mt-2">Save Internal Note</button></form>}</div></section>
  </section>;
}
