import { useEffect, useState } from "react";
import { ApiError, ITPriority, RequestedPriority, StaffQueueItem, StaffQueueQuery, TicketStatus, getStaffTickets } from "./api.js";

const statuses: TicketStatus[] = ["NEW", "OPEN", "IN_PROGRESS", "WAITING_FOR_REQUESTER", "RESOLVED", "CLOSED", "REOPENED", "CANCELLED"];
const requestedPriorities: RequestedPriority[] = ["LOW", "MEDIUM", "HIGH"];
const itPriorities: ITPriority[] = ["NOT_SET", "LOW", "MEDIUM", "HIGH", "URGENT"];

export function StaffTicketQueue({ onOpenTicket }: { onOpenTicket?: (ticketId: number) => void }) {
  const [query, setQuery] = useState<StaffQueueQuery>({ page: 1, pageSize: 10, sortBy: "updatedAt", sortOrder: "desc" });
  const [items, setItems] = useState<StaffQueueItem[]>([]); const [totalPages, setTotalPages] = useState(1); const [totalItems, setTotalItems] = useState(0);
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; setLoading(true); setError(""); getStaffTickets(query).then((result) => { if (active) { setItems(result.items); setTotalPages(result.totalPages); setTotalItems(result.totalItems); } }).catch((reason: unknown) => { if (active) setError(reason instanceof ApiError ? reason.message : "The Ticket queue is unavailable. Please try again."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [query]);
  const update = (changes: Partial<StaffQueueQuery>) => setQuery((current) => ({ ...current, ...changes, page: changes.page ?? 1 }));
  return <section aria-labelledby="queue-title"><div className="d-flex flex-wrap align-items-center gap-2 mb-3"><div><h1 id="queue-title" className="h2 mb-1">Ticket Queue</h1><p className="text-muted mb-0">{totalItems} ticket{totalItems === 1 ? "" : "s"} in the operational queue.</p></div></div>
    <div className="card card-body mb-3"><div className="row g-3"><div className="col-md-4"><label className="form-label" htmlFor="queue-search">Search</label><input id="queue-search" className="form-control" value={query.search ?? ""} onChange={(event) => update({ search: event.target.value })} placeholder="Ticket number or summary" /></div>
      <Select label="Status" value={query.status ?? ""} options={statuses} onChange={(status) => update({ status: status as TicketStatus || undefined })} />
      <Select label="Requested priority" value={query.requestedPriority ?? ""} options={requestedPriorities} onChange={(requestedPriority) => update({ requestedPriority: requestedPriority as RequestedPriority || undefined })} />
      <Select label="IT priority" value={query.itPriority ?? ""} options={itPriorities} onChange={(itPriority) => update({ itPriority: itPriority as ITPriority || undefined })} />
      <div className="col-md-3"><label className="form-label" htmlFor="queue-sort">Sort</label><select id="queue-sort" className="form-select" value={`${query.sortBy}:${query.sortOrder}`} onChange={(event) => { const [sortBy, sortOrder] = event.target.value.split(":"); update({ sortBy: sortBy as StaffQueueQuery["sortBy"], sortOrder: sortOrder as "asc" | "desc" }); }}><option value="updatedAt:desc">Last updated (newest)</option><option value="updatedAt:asc">Last updated (oldest)</option><option value="ticketNumber:asc">Ticket number</option><option value="currentStatus:asc">Status</option></select></div>
    </div></div>
    {loading ? <p role="status">Loading Ticket Queue...</p> : error ? <div className="alert alert-danger" role="alert">{error}</div> : items.length === 0 ? <div className="alert alert-info" role="status">{query.search || query.status || query.requestedPriority || query.itPriority ? "No Tickets match these filters." : "There are no Tickets in the queue."}</div> : <><div className="table-responsive d-none d-md-block"><table className="table align-middle"><thead><tr><th>Ticket</th><th>Summary</th><th>Requester</th><th>Status</th><th>Priority</th><th>Owner</th><th>Updated</th><th><span className="visually-hidden">Action</span></th></tr></thead><tbody>{items.map((ticket) => <tr key={ticket.id}><td>{ticket.ticketNumber}</td><td>{ticket.summary}</td><td>{ticket.requesterUser?.name ?? "Unavailable"}</td><td><span className="badge text-bg-secondary">{ticket.currentStatus}</span></td><td>{ticket.requestedPriority} / {ticket.itPriority}</td><td>{ticket.owner?.name ?? "Unassigned"}</td><td>{new Date(ticket.updatedAt).toLocaleString()}</td><td><button className="btn btn-sm btn-outline-success" onClick={() => onOpenTicket?.(ticket.id)}>Open detail</button></td></tr>)}</tbody></table></div><div className="d-md-none">{items.map((ticket) => <article className="card card-body mb-2" key={ticket.id}><strong>{ticket.ticketNumber}</strong><span>{ticket.summary}</span><small>{ticket.currentStatus} · {ticket.requestedPriority} / {ticket.itPriority}</small><small>Requester: {ticket.requesterUser?.name ?? "Unavailable"} · Owner: {ticket.owner?.name ?? "Unassigned"}</small><button className="btn btn-outline-success mt-2" onClick={() => onOpenTicket?.(ticket.id)}>Open detail</button></article>)}</div></>}
    <nav className="d-flex align-items-center gap-2" aria-label="Queue pagination"><button className="btn btn-outline-success" disabled={loading || (query.page ?? 1) <= 1} onClick={() => update({ page: (query.page ?? 1) - 1 })}>Previous</button><span>Page {query.page} of {totalPages}</span><button className="btn btn-outline-success" disabled={loading || (query.page ?? 1) >= totalPages} onClick={() => update({ page: (query.page ?? 1) + 1 })}>Next</button></nav>
  </section>;
}
function Select({ label, value, options, onChange }: { label: string; value: string; options: readonly string[]; onChange: (value: string) => void }) { const id = `queue-${label.replaceAll(" ", "-").toLowerCase()}`; return <div className="col-md-2"><label className="form-label" htmlFor={id}>{label}</label><select id={id} className="form-select" value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{options.map((option) => <option key={option}>{option}</option>)}</select></div>; }
