import { FormEvent, useCallback, useEffect, useState } from "react";
import { AuthUser, createAdminUser, getAdminUsers, ManagedUser, resetAdminPassword, updateAdminUser, UserRole } from "./api.js";

const roles: UserRole[] = ["REQUESTER", "IT_STAFF", "ADMINISTRATOR"];
const passwordHint = "At least 12 characters with upper, lower, number, and symbol.";

export function UserManagement({ user }: { user: AuthUser }) {
  const [items, setItems] = useState<ManagedUser[]>([]);
  const [search, setSearch] = useState(""); const [role, setRole] = useState("");
  const [editing, setEditing] = useState<ManagedUser | null>(null); const [resetting, setResetting] = useState<ManagedUser | null>(null);
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems(await getAdminUsers(search, role)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to retrieve users."); } finally { setLoading(false); } }, [search, role]);
  useEffect(() => { void load(); }, [load]);

  async function create(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setMessage(""); setError(""); const form = event.currentTarget; const data = new FormData(form);
    try { await createAdminUser({ name: String(data.get("name")), email: String(data.get("email")), role: String(data.get("role")) as UserRole, active: data.get("active") === "on", initialPassword: String(data.get("initialPassword")) }); setMessage("User created. They must change the initial password at next login."); form.reset(); await load(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to create user."); }
  }
  async function saveEdit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editing) return; setMessage(""); setError(""); const data = new FormData(event.currentTarget);
    try { await updateAdminUser(editing.id, { name: String(data.get("name")), email: String(data.get("email")), role: String(data.get("role")) as UserRole, active: editing.id === user.id || data.get("active") === "on" }); setEditing(null); setMessage("User details updated."); await load(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update user."); }
  }
  async function resetPassword(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!resetting) return; setMessage(""); setError(""); const data = new FormData(event.currentTarget);
    try { await resetAdminPassword(resetting.id, String(data.get("initialPassword"))); setResetting(null); setMessage("Initial password reset. Existing sessions were revoked and a password change is required at next login."); await load(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to reset password."); }
  }

  return <section>
    <header className="mb-4"><h1>User Management</h1><p className="text-secondary mb-0">Create accounts and safely maintain roles, access, and initial passwords.</p></header>
    {message && <div className="alert alert-success" role="status">{message}</div>}{error && <div className="alert alert-danger" role="alert">{error}</div>}
    <div className="row g-3 mb-4"><div className="col-12 col-md-8"><label className="form-label" htmlFor="user-search">Search users</label><input id="user-search" className="form-control" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name or email" /></div><div className="col-12 col-md-4"><label className="form-label" htmlFor="user-role">Role</label><select id="user-role" className="form-select" value={role} onChange={(event) => setRole(event.target.value)}><option value="">All roles</option>{roles.map((value) => <option key={value}>{value}</option>)}</select></div></div>
    {loading ? <p role="status">Loading users...</p> : items.length === 0 ? <p role="status" className="text-secondary">No users match these filters.</p> : <div className="table-responsive mb-4"><table className="table align-middle"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th><span className="visually-hidden">Actions</span></th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.name}{item.id === user.id && <span className="badge text-bg-light ms-2">You</span>}</td><td>{item.email}</td><td>{item.role}</td><td><span className={`badge ${item.isActive ? "text-bg-success" : "text-bg-secondary"}`}>{item.isActive ? "Active" : "Inactive"}</span>{item.mustChangePassword && <small className="d-block text-secondary">Password change required</small>}</td><td><div className="d-flex flex-wrap gap-2 justify-content-end"><button className="btn btn-outline-success btn-sm" onClick={() => { setEditing(item); setResetting(null); }}>Edit</button><button className="btn btn-outline-secondary btn-sm" onClick={() => { setResetting(item); setEditing(null); }}>Reset password</button></div></td></tr>)}</tbody></table></div>}
    {editing && <form className="card card-body mb-4" onSubmit={saveEdit}><div className="d-flex justify-content-between"><h2 className="h5">Edit {editing.name}</h2><button type="button" className="btn-close" aria-label="Cancel editing" onClick={() => setEditing(null)} /></div><div className="row g-3"><div className="col-12 col-md-6"><label className="form-label" htmlFor="edit-name">Name</label><input id="edit-name" className="form-control" name="name" defaultValue={editing.name} minLength={2} maxLength={120} required /></div><div className="col-12 col-md-6"><label className="form-label" htmlFor="edit-email">Email</label><input id="edit-email" className="form-control" name="email" type="email" defaultValue={editing.email} required /></div><div className="col-12 col-md-6"><label className="form-label" htmlFor="edit-role">Role</label><select id="edit-role" className="form-select" name="role" defaultValue={editing.role}>{roles.map((value) => <option key={value}>{value}</option>)}</select></div><div className="col-12 col-md-6 d-flex align-items-end"><div className="form-check mb-2"><input id="edit-active" className="form-check-input" name="active" type="checkbox" defaultChecked={editing.isActive} disabled={editing.id === user.id} /><label className="form-check-label" htmlFor="edit-active">Active account</label>{editing.id === user.id && <small className="d-block text-secondary">You cannot deactivate your own account.</small>}</div></div></div><button className="btn btn-success mt-3 align-self-start">Save changes</button></form>}
    {resetting && <form className="card card-body mb-4" onSubmit={resetPassword}><div className="d-flex justify-content-between"><h2 className="h5">Reset password for {resetting.name}</h2><button type="button" className="btn-close" aria-label="Cancel password reset" onClick={() => setResetting(null)} /></div><label className="form-label" htmlFor="reset-password">New initial password</label><input id="reset-password" className="form-control" name="initialPassword" type="password" minLength={12} maxLength={128} aria-describedby="reset-password-hint" required /><div id="reset-password-hint" className="form-text">{passwordHint}</div><button className="btn btn-success mt-3 align-self-start">Reset initial password</button></form>}
    <form className="card card-body" onSubmit={create}><h2 className="h5">Create user</h2><div className="row g-3"><div className="col-12 col-md-6"><label className="form-label" htmlFor="create-name">Name</label><input id="create-name" className="form-control" name="name" minLength={2} maxLength={120} required /></div><div className="col-12 col-md-6"><label className="form-label" htmlFor="create-email">Email</label><input id="create-email" className="form-control" name="email" type="email" required /></div><div className="col-12 col-md-6"><label className="form-label" htmlFor="create-role">Role</label><select id="create-role" className="form-select" name="role">{roles.map((value) => <option key={value}>{value}</option>)}</select></div><div className="col-12 col-md-6"><label className="form-label" htmlFor="create-password">Initial password</label><input id="create-password" className="form-control" name="initialPassword" type="password" minLength={12} maxLength={128} aria-describedby="create-password-hint" required /><div id="create-password-hint" className="form-text">{passwordHint}</div></div><div className="col-12"><div className="form-check"><input id="create-active" className="form-check-input" name="active" type="checkbox" defaultChecked /><label className="form-check-label" htmlFor="create-active">Active account</label></div></div></div><button className="btn btn-success mt-3 align-self-start">Create user</button></form>
  </section>;
}
